### ISSUE TITLE
Mamba MQAR evauation

### ISSUE THREAD

**Issue by xtwigs** [HazyResearch/zoology#10]
Hello, great work on the paper!
It greatly coincides with a line of work I was considering pursuing.

Any chance you could include the recently proposed Mamba architecture in the MQAR experiments? I would believe it would still perform worse than standard attention but wanted to confirm this to be the case.

**Comment by simran-arora** [comment]
Hi, we have included MQAR Mamba experiments in the blogposts: https://hazyresearch.stanford.edu/blog/2023-12-11-zoology1-analysis
See the "Extended Analysis" section. 
Mamba is also supported in this repo -- you can launch experiments here to reproduce, following the instructions to launch experiments that are mentioned in the README: https://github.com/HazyResearch/zoology/blob/240196eec608a178038d2ba5dc21ccf948f48992/zoology/experiments/mqar_d_model.py#L141

**Comment by xtwigs** [comment]
Thank you for the reply, I wasn't aware of both the blog post and the Based model!

I'll definitely consider adding it to my experiments.
