### ISSUE TITLE
Cannot run Based model

### ISSUE THREAD

**Issue by Cranial-XIX** [HazyResearch/zoology#15]
Hi, 

Thanks for this good work! I cannot run the "Based" model using the `figure2.py` inside the experiment folder. I think the problem is that in the config there are only 2 configs for 2 layers, but the model requires 4 layers if it is not the standard attention.

**Comment by infiniteperplexity** [comment]
I'm experiencing the same issue.

**Comment by simran-arora** [comment]
Hi, you could reference this config for the plots released in the blogpost on Based: https://github.com/HazyResearch/zoology/blob/states/zoology/experiments/num_kv.py

We will clean up the figure 2 config, thanks for pointing it out.
