### ISSUE TITLE
State Mixer

### ISSUE THREAD

**Issue by edixiong** [HazyResearch/zoology#16]
In the code it seems like (e.g., for attention) the state mixer (channel mixer) is torch.nn.Identity is there a reason not to use the original setting (e.g., FFN with width=4)? Also, after making this change, is setting layer for attention to be 2 and layers for other models to be 4 still a fair comparison? (since these layer-wise differences is to make number of parameters to be roughly the same). Thanks!

**Comment by simran-arora** [comment]
Hi thanks for the question! We notice that the state mixer choice doesn't affect the trend for this study. If you use a different synthetic, for instance with more stateful key-value mappings across the examples, then it could be a good to add back the MLPs. We reported across model dimension for most experiments to capture the scaling trends, but this does not mean that at 512 model dimension the sequence mixers are parameter matched. e

**Comment by edixiong** [comment]
Thanks!
