### ISSUE TITLE
Two `head_num` variables?

### ISSUE THREAD

**Issue by deklanw** [HazyResearch/zoology#20]
https://github.com/HazyResearch/zoology/blob/main/zoology/mixers/based.py#L100-L101

Why are there two different variables for number of heads? Is this a mistake?

**Comment by simran-arora** [comment]
Hi thanks for the question! Actually the q vs. kv's can be split into different numbers of heads! This is standard in Llama etc. (https://github.com/huggingface/transformers/blob/871ba71dfa04f9d37a4f32e1f962a1199a5cf51a/src/transformers/models/llama/modeling_llama.py#L271) 
So far we've set them equal, but potentially interesting to explore alternate head dimensions. Hope this helps!

**Comment by deklanw** [comment]
Oh, for grouped query attention? I see thanks

```python
d_model = 512
l_max = 1024
model = Based(d_model=d_model, l_max=l_max, num_heads=8, num_key_value_heads=4, feature_dim=16)

model(torch.rand(1, l_max, d_model))
```

this fails, though with 

```
--> [222](vscode-notebook-cell:?execution_count=12&line=222)     k = k.view(b, l, self.num_key_value_heads, self.feature_dim).transpose(1, 2)
    [223](vscode-notebook-cell:?execution_count=12&line=223)     v = v.view(b, l, self.num_key_value_heads, self.head_dim).transpose(1, 2)
    [225](vscode-notebook-cell:?execution_count=12&line=225) # Linear attention

RuntimeError: shape '[1, 1024, 4, 16]' is invalid for input of size 131072
```

If I change `num_key_value_heads` to also be 8 it works.

**Comment by simran-arora** [comment]
We don't currently have GQA implemented in the repo, sorry! We may add it soon!
