### ISSUE TITLE
On index bug-fix of AR experiments script and corresponding paper results

### ISSUE THREAD

**Issue by atsushi3110** [HazyResearch/zoology#21]
Hi, thanks for your sharing great code base.

In the latest version of paper in arxiv,  did all experiments run after the following bug-fix ?

https://github.com/HazyResearch/zoology/commit/967684304b9fb0d977289bacadedb3ab407214cd

![image](https://github.com/HazyResearch/zoology/assets/19440811/992fb0f6-aec5-43a1-8e05-509f583666a5)

**Comment by simran-arora** [comment]
Hi we actually used the multi-query associative recall data in all the paper experiments (not the _ar). If you checkout the same file you should see that data constructor! Let us know if you have any more questions
