### ISSUE TITLE
Potential bug in data generation code?

### ISSUE THREAD

**Issue by lwang2070** [HazyResearch/zoology#6]
I was looking through the data generation code for the synthetic data when I found the following [line](https://github.com/HazyResearch/zoology/blob/23f6bef6f9057f74dc10c8e19abb26ba4554481a/zoology/data/associative_recall.py#L139)

```
    rows = np.tile(np.arange(num_examples), (3, 1)).T  
```

It seems that the code assumes `num_queries==3`? It is perhaps better to change 3 into `num_queries`.

Please correct me if my understanding is wrong. Thanks!

**Comment by seyuboglu** [comment]
thanks for pointing this out! fixed 

note we recently added the general version `associative_recall` that works for mqar and regular ar. If you're reproducing results from the paper/blogpost, you can use `multiquery_ar`, which is what we used for the paper and is more tried.
