### ISSUE TITLE
Positional embedding in based model?

### ISSUE THREAD

**Issue by fanghgit** [HazyResearch/zoology#7]
Great work! But I have a question on positional embedding.

I find that there is no positional embedding used in the based model. I wonder if you plan to add positional embedding in the future? And why Based model can outperform Transformer without ROPE (as claimed in the zoloogy [blog](https://hazyresearch.stanford.edu/blog/2023-12-11-zoology2-based)) ?

**Comment by simran-arora** [comment]
Hi thanks for the question -- we used rotary positional embeddings in the reported downstream Pile experiments.
