### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by thomasj02** [HazyResearch/zoology#9]
The second zoology blog post has this text:
> we compare the PyTorch reference implementation provided [here](https://github.com/HazyResearch/zoology/blob/main/based_refs/causal_ref.py), with the CUDA code and observe the following speedups! Note that the PyTorch code runs out of memory at N=32768 and BS=4. Experiments are run on an 80GB A100 GPU.

Unfortunately that link doesn't seem to work anymore!

On a related note, is the CUDA code available?

**Comment by simran-arora** [comment]
Hi they got removed in a refactor -- here you go: https://github.com/HazyResearch/zoology/tree/d0c2fa46005c638b525f29fdeb9fc6ece06fdd28/based_refs

We will release the CUDA code with full release! The structure of ```linear_attn_ref.py''' at the link above shows the python forward and backward pass for the CUDA algorithm we use.
